ALTER TABLE players ADD COLUMN global_reputation INTEGER NOT NULL DEFAULT 0;
ALTER TABLE players ADD COLUMN local_reputation_json TEXT NOT NULL DEFAULT '{}';
ALTER TABLE players ADD COLUMN renown INTEGER NOT NULL DEFAULT 0;
ALTER TABLE players ADD COLUMN title TEXT NOT NULL DEFAULT 'Wędrowiec';
ALTER TABLE players ADD COLUMN crimes_json TEXT NOT NULL DEFAULT '{}';
ALTER TABLE players ADD COLUMN wanted_level INTEGER NOT NULL DEFAULT 0;
ALTER TABLE players ADD COLUMN wanted_posts_json TEXT NOT NULL DEFAULT '[]';
