from __future__ import annotations

NPC_COMBAT_STYLE_BY_VNUM: dict[str, str] = {
    "meekhan_soldier": "defensywny",
    "merchant": "ostrozny",
    "mountain_troll": "brutalny",
    "wolf": "ofensywny",
    "astergard_guard": "defensywny",
    "innkeeper": "ostrozny",
    "blacksmith": "defensywny",
    "farmer": "zrownowazony",
    "fisherman": "zrownowazony",
    "traveler": "zrownowazony",
    "child": "zrownowazony",
    "beggar": "zrownowazony",
    "carpenter": "zrownowazony",
    "tanner": "zrownowazony",
    "bowyer": "zrownowazony",
    "armorer": "defensywny",
    "dockhand": "zrownowazony",
    "miller": "zrownowazony",
    "priest_aide": "zrownowazony",
    "watch_sergeant": "defensywny",
    "customs_clerk": "zrownowazony",
    "fishmonger": "zrownowazony",
    "woodcutter": "zrownowazony",
    "urchin": "zrownowazony",
    "vagrant": "zrownowazony",
    "podgrodzie_woznica": "zrownowazony",
    "podgrodzie_karczmarz": "ostrozny",
    "podgrodzie_karczmarka": "zrownowazony",
    "podgrodzie_piekarz": "zrownowazony",
    "podgrodzie_handlarz": "ostrozny",
    "podgrodzie_przekupka": "ostrozny",
    "podgrodzie_kowal": "defensywny",
    "podgrodzie_pomocnik_kowala": "zrownowazony",
    "podgrodzie_straznik_miejski": "defensywny",
    "podgrodzie_rybak": "zrownowazony",
    "podgrodzie_dziecko": "zrownowazony",
    "podgrodzie_zebrak": "zrownowazony",
    "podgrodzie_pielgrzym": "ostrozny",
    "podgrodzie_chlop": "zrownowazony",
    "podgrodzie_chlopka": "zrownowazony",
}


def combat_style_for_vnum(vnum: str) -> str:
    return NPC_COMBAT_STYLE_BY_VNUM.get(vnum, "zrownowazony")
